# Generated by Django 2.0.2 on 2018-02-16 12:27

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('name', models.CharField(max_length=200)),
                ('email', models.EmailField(max_length=200, primary_key=True, serialize=False, unique=True)),
                ('signup_type', models.CharField(max_length=1)),
                ('message', models.TextField(max_length=200)),
                ('robot', models.BooleanField(default=False)),
            ],
        ),
    ]
