# Generated by Django 2.0.2 on 2018-02-15 22:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Signup',
            fields=[
                ('name', models.CharField(max_length=200)),
                ('email', models.EmailField(max_length=200, primary_key=True, serialize=False, unique=True)),
                ('signup_type', models.CharField(max_length=1)),
                ('message', models.TextField(max_length=200)),
            ],
        ),
    ]
