# Generated by Django 2.0.2 on 2018-02-17 18:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_auto_20180216_1531'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contact',
            name='robot',
        ),
        migrations.RemoveField(
            model_name='contact',
            name='signup_type',
        ),
        migrations.AddField(
            model_name='contact',
            name='not_a_robot',
            field=models.BooleanField(default=False),
        ),
    ]
